## 1. Elementwise Operations


In [1]:
import numpy as np

In [2]:
a = np.array(
    [
        [4,5,6],
        [1,2,4]
    ]
)
b = np.array([[8,6,0],[3,2,4]])
c = np.array([[8,4,0],[3,11,4]])

In [3]:
a, b 

(array([[4, 5, 6],
        [1, 2, 4]]),
 array([[8, 6, 0],
        [3, 2, 4]]))

### Arithmetic Operations

In [4]:
# a + b
np.add(a,b)

array([[12, 11,  6],
       [ 4,  4,  8]])

In [5]:
# a - b
np.subtract(a,b)

array([[-4, -1,  6],
       [-2,  0,  0]])

In [6]:
# a ** 2
np.pow(a, 2)

array([[16, 25, 36],
       [ 1,  4, 16]])

In [7]:
# a % b
quo , rem = np.divmod(a,b)
quo

/tmp/ipykernel_111330/1124160517.py:2: RuntimeWarning: divide by zero encountered in divmod
  quo , rem = np.divmod(a,b)


array([[0, 0, 0],
       [0, 1, 1]])

In [8]:
rem

array([[4, 5, 0],
       [1, 0, 0]])

### Trignometric

In [9]:
np.sin(a)

array([[-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.84147098,  0.90929743, -0.7568025 ]])

In [10]:
cot = 1 / np.tan(a)
cot

array([[ 0.86369115, -0.29581292, -3.436353  ],
       [ 0.64209262, -0.45765755,  0.86369115]])

### Rounding operations

In [11]:
np.around(cot, 2)

array([[ 0.86, -0.3 , -3.44],
       [ 0.64, -0.46,  0.86]])

In [12]:
np.floor(cot)

array([[ 0., -1., -4.],
       [ 0., -1.,  0.]])

In [13]:
np.ceil(cot)

array([[ 1., -0., -3.],
       [ 1., -0.,  1.]])

## 2. Matrix Operations


In [16]:
b = np.random.randint(0,10, (3,4))

In [19]:
a,b

(array([[4, 5, 6],
        [1, 2, 4]]),
 array([[3, 5, 3, 0],
        [8, 3, 8, 9],
        [2, 4, 7, 5]]))

In [17]:
# a @ b
res = np.dot(a,b)

In [18]:
res

array([[64, 59, 94, 75],
       [27, 27, 47, 38]])

In [23]:
# a.T
np.transpose(a)

array([[4, 1],
       [5, 2],
       [6, 4]])

In [24]:
np.trace(b) # Diagonal sum

np.int64(13)

In [27]:
# Inverse of an matrix

sq = np.random.randint(0,10, (3,3))
a_det = np.linalg.det(sq)

np.float64(79.99999999999997)

In [29]:
inv_sq = np.linalg.inv(sq)

In [36]:
np.dot(sq, inv_sq).round()

array([[ 1.,  0., -0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

Solve Equation : `4x + 2y = 8` , `5x + 3y = 9`

In [37]:
a = np.array(
    [
        [4,2],
        [5,3]
    ]
)
b = np.array([8,9])

In [38]:
a_inv = np.linalg.inv(a)

In [40]:
np.dot(a_inv,b)

array([ 3., -2.])

In [41]:
# x = 3, y = -2

In [42]:
## Array Broadcasting

In [45]:
a * b

array([[32, 18],
       [40, 27]])