In [2]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 18.2 MB/s eta 0:00:00m eta 0:00:010:00:01


In [3]:
import numpy as np

In [4]:
np.__version__

'2.4.0'

### Creating Numpy array

In [5]:
list1 = [2,3,4]

In [6]:
arr1 = np.array(list1)

In [7]:
arr1

array([2, 3, 4])

In [8]:
arr1.shape

(3,)

In [9]:
arr1.ndim

1

In [19]:
list1 = [[[2,3,4],[6,7,8], [6,8,0]],[[2,3,4],[6,7,8], [6,8,0]]]
arr1 = np.array(list1)

In [20]:
arr1

array([[[2, 3, 4],
        [6, 7, 8],
        [6, 8, 0]],

       [[2, 3, 4],
        [6, 7, 8],
        [6, 8, 0]]])

In [21]:
arr1.shape

(2, 3, 3)

In [22]:
arr1.ndim

3

NumPy arrays can be created in several ways. Here are some of the most common methods:

- `array()`: Creates NumPy arrays from Python lists
- `zeros()`: Creates NumPy arrays with all elements initialized to 0
- `ones()`: Creates NumPy arrays with all elements initialized to 1
- `full()`: Creates an array with all elements initialized to same user-specified value
- `arange()`: Creates NumPy arrays with a sequence of values (similar to python range() function)
- `linspace()`: Creates NumPy arrays with a sequence of evenly spaced values
- `diag()`: Creates NumPy array with the provided list of numbers as the diagonal elements and zeros elsewhere
- `eye()`: Creates NumPy array with ones on the diagonal and zeros elsewhere
- `identity()`: Creates an identity matrix
- `random.rand()`: Creates NumPy array of random numbers sampled from a uniform distribution

In [30]:
np.zeros((2, 3, 2), dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [33]:
np.full((3,4), fill_value=6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [34]:
np.arange(1,90,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

In [43]:
arr2 = np.linspace( (0,1,2) ,(10,20,30), num = 5)
arr2

array([[ 0.  ,  1.  ,  2.  ],
       [ 2.5 ,  5.75,  9.  ],
       [ 5.  , 10.5 , 16.  ],
       [ 7.5 , 15.25, 23.  ],
       [10.  , 20.  , 30.  ]])

In [42]:
arr2.shape

(5, 3)

In [44]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [45]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
np.random.randint(0,10,size = (2,3))

array([[7, 8, 8],
       [2, 1, 6]])

In [51]:
np.random.randint(0,50,size = (4,2,3))

array([[[21, 48,  2],
        [31, 46, 17]],

       [[10, 28, 25],
        [29, 44, 27]],

       [[43,  2, 42],
        [ 7, 46, 24]],

       [[35, 20, 48],
        [32, 17,  6]]])